name = "monochrome"
kind = "dark"

[hues]
# We cheat and add some colors for vcs/diff
red = 15.0
yellow = 98.0
green = 135.0

[fg]
lightness = 0.73
chroma = 0.05

[bg]
lightness = 0.30
chroma = 0.05

[colors]
fg = [ 0.73, 0.00, 86 ]
bg = [ 0.12, 0.00, 86 ]

[themes.ui]
fg = "fg"
fg_dim = { color = "fg", mix = ["bg", 0.1] }
fg_very_dim = { color = "fg", mix = ["bg", 0.3] }

bg = "bg"
bg_visual =        { color = "bg", lighten_absolute = 0.15 }
bg_highlight =     { color = "bg", lighten_absolute = 0.20 }
bg_highlight_dim = { color = "bg", lighten_absolute = 0.10 }
bg_border =        { color = "fg" }
bg_gutter =        { color = "bg", lighten_absolute = 0.10 }
bg_dim =           { color = "bg", lighten_absolute = -0.05 }
bg_selected =      { color = "bg", lighten_absolute = 0.10 }

float_bg =     { color = "bg", lighten_absolute = 0.03 }
float_fg =     { color = "fg", lighten_absolute = 0.03 }
float_border = "fg"

pmenu_bg =          { color = "bg", lighten_absolute = 0.1 }
pmenu_fg =          { color = "fg", lighten_absolute = 0.1 }
pmenu_fg_selected = { color = "fg", lighten_absolute = 0.1 }
pmenu_bg_selected = { color = "bg", lighten_absolute = 0.25 }

special = "fg"
nontext = { color = "fg", mix = ["bg", 0.3] }

[themes.syn]
string =   { color = "fg", lighten_absolute = 0.12 }
number =   { color = "fg", lighten_absolute = 0.12 }
constant = { color = "fg", lighten_absolute = 0.12 }
regex =    { color = "fg", lighten_absolute = 0.12 }
preproc =  { color = "fg", lighten_absolute = 0.12 }
type =        "fg"
variable =    "fg"
identifier =  "fg"
parameter =   "fg"
function =    "fg"
constructor = "fg"
statement =   "fg"
keyword =     { color = "fg", lighten_absolute = -0.05 }
operator =    { color = "fg", lighten_absolute = -0.05 }
deprecated =  { color = "fg", lighten_absolute = -0.10 }
comment =     { color = "fg", lighten_absolute = -0.10 }
special =     { color = "fg", lighten_absolute = 0.10 }
punctuation = { color = "fg", lighten_absolute = -0.10 }

[themes.diagnostics]
error =   { color = "fg.red" }
warning = { color = "fg.yellow" }
info =    { color = "fg.yellow" }
hint =    { color = "fg.green" }
ok =      { color = "fg.green" }

[themes.vcs]
removed = "fg.red"
added = "fg.green"
changed = "fg.yellow"

[themes.diff]
removed = "bg.red"
added = "bg.green"
changed = "bg.yellow"
text = "bg"

[inverse]
gamma = 1.1
lighten_absolute = 0.02

[highlights]
